// Zencrepes configuration for that entity
const entity = 'githubVulnerabilities';
const config = {
  id: entity,
  name: 'Vulnerabilities',
  platform: 'github',
  active: true,
  facets: [
    {
      facetType: 'date',
      field: 'createdAt',
      name: 'Created',
      nullValue: 'EMPTY',
      default: false,
    },
    {
      facetType: 'date',
      field: 'dismissedAt',
      name: 'Dismissed',
      nullValue: 'EMPTY',
      default: false,
    },
    {
      facetType: 'term',
      field: 'securityVulnerability.severity',
      name: 'Severity',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'securityVulnerability.package.ecosystem',
      name: 'Ecosystem',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'repository.owner.login',
      name: 'Organization',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'repository.name.keyword',
      name: 'Repository',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'dismisser.login',
      name: 'Dismisser',
      nullValue: 'NO DISMISSER',
      nullFilter:
        '{"op":"in","content":{"field":"dismisser","value":["__missing__"]}}',
      default: true,
    },
    {
      facetType: 'term',
      field: 'securityVulnerability.package.name',
      name: 'Package',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'vulnerableManifestFilename',
      name: 'Filename',
      nullValue: 'EMPTY',
      default: true,
    },
  ],
  tableConfig: {
    itemsType: 'Github Vulnerabilities',
    defaultSortField: 'createdAt',
    columns: [
      {
        name: 'id',
        field: 'id',
        fieldType: 'string',
        sortField: 'id',
        sortable: false,
        default: false,
      },
      {
        name: 'Created At',
        field: 'createdAt',
        fieldType: 'date',
        sortField: 'createdAt',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Org',
        field: 'repository.owner.login',
        fieldType: 'string',
        sortField: 'repository.owner.login',
        linkField: 'repository.owner.url',
        sortable: true,
        default: true,
      },
      {
        name: 'Repo',
        field: 'repository.name',
        fieldType: 'string',
        sortField: 'repository.name.keyword',
        linkField: 'repository.url',
        sortable: true,
        default: true,
      },
      {
        name: 'Ecosystem',
        field: 'securityVulnerability.package.ecosystem',
        fieldType: 'string',
        sortField: 'securityVulnerability.package.ecosystem',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Package',
        field: 'securityVulnerability.package.name',
        fieldType: 'string',
        sortField: 'securityVulnerability.package.name',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Summary',
        field: 'securityVulnerability.advisory.summary',
        fieldType: 'string',
        sortField: 'securityVulnerability.advisory.summary.keyword',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Dismissed At',
        field: 'dismissedAt',
        fieldType: 'date',
        sortField: 'dismissedAt',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Dismisser',
        field: 'dismisser.login',
        fieldType: 'string',
        sortField: 'dismisser.login',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Url',
        field: 'repository.url',
        fieldType: 'link',
        sortField: null,
        linkField: null,
        sortable: false,
        default: false,
      },
    ],
  },
};

export default config;
