// Zencrepes configuration for that entity
const entity = 'githubMavenPoms';
const config = {
  id: entity,
  name: 'Maven POM',
  platform: 'github',
  active: true,
  facets: [
    {
      facetType: 'date',
      field: 'createdAt',
      name: 'Repo Created',
      nullValue: 'n/a',
      nullFilter: '',
      default: true,
    },
    {
      facetType: 'date',
      field: 'updatedAt',
      name: 'Repo Updated',
      nullValue: 'n/a',
      nullFilter: '',
      default: true,
    },
    {
      facetType: 'date',
      field: 'pushedAt',
      name: 'Repo Pushed',
      nullValue: 'n/a',
      nullFilter: '',
      default: true,
    },
    {
      facetType: 'term',
      field: 'owner.login',
      name: 'Organization',
      nullValue: 'n/a',
      nullFilter: '',
      default: true,
    },  
    {
      facetType: 'term',
      field: 'repositoryTopics.edges.node.topic.name',
      name: 'Topics',
      nullValue: 'NO TOPICS',
      nullFilter:
        '{"op":"<=","content":{"field":"repositoryTopics.totalCount","value":0}}',
      default: true,
    },    
    {
      facetType: 'term',
      field: 'defaultBranchRef.name.keyword',
      name: 'Default Branch',
      nullValue: 'NONE',
      nullFilter:
        '{"op":"in","content":{"field":"defaultBranchRef.name.keyword","value":["__missing__"]}}',
      default: true,
    },    
    {
      facetType: 'term',
      field: 'lastCommitMainBranch.author.email',
      name: 'Last Committer',
      nullValue: 'NONE',
      nullFilter:
        '{"op":"in","content":{"field":"lastCommitMainBranch.author.email.keyword","value":["__missing__"]}}',
      default: true,
    },
    {
      facetType: 'term',
      field: 'lastCommitMainBranch.messageHeadline.keyword',
      name: 'Last Commit msg',
      nullValue: 'NONE',
      nullFilter:
        '{"op":"in","content":{"field":"lastCommitMainBranch.messageHeadline.keyword","value":["__missing__"]}}',
      default: false,
    },    
    {
      facetType: 'term',
      field: 'pom.parent.artifactId',
      name: 'Parent Artifact',
      nullValue: 'NONE',
      nullFilter:
        '{"op":"in","content":{"field":"pom.parent.artifactId","value":["__missing__"]}}',
      default: true,
    },        
    {
      facetType: 'term',
      field: 'pom.parent.version',
      name: 'Parent Version',
      nullValue: 'NONE',
      nullFilter:
        '{"op":"in","content":{"field":"pom.parent.version","value":["__missing__"]}}',
      default: true,
    },      
    {
      facetType: 'boolean',
      field: 'isArchived',
      name: 'Archived',
      nullValue: 'EMPTY',
      nullFilter: '',
      default: true,
    },
    {
      facetType: 'boolean',
      field: 'hasPom',
      name: 'Has POM',
      nullValue: 'EMPTY',
      nullFilter: '',
      default: true,
    },
    {
      facetType: 'boolean',
      field: 'hasParent',
      name: 'Has Parent',
      nullValue: 'EMPTY',
      nullFilter: '',
      default: true,
    },    

  ],
  tableConfig: {
    itemsType: 'Github Maven POMs',
    defaultSortField: 'pushedAt',
    columns: [
      {
        name: 'id',
        field: 'id',
        fieldType: 'string',
        sortField: 'id',
        sortable: false,
        default: false,
      },
      {
        name: 'Pushed At',
        field: 'pushedAt',
        fieldType: 'date',
        sortField: 'pushedAt',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Org',
        field: 'owner.login',
        fieldType: 'string',
        sortField: 'owner.login',
        linkField: 'owner.url',
        sortable: true,
        default: true,
      },
      {
        name: 'Repo Name',
        field: 'name',
        fieldType: 'string',
        sortField: 'name.keyword',
        linkField: 'url',
        sortable: true,
        default: true,
      },
      {
        name: 'Default branch',
        field: 'defaultBranchRef.name',
        fieldType: 'string',
        sortField: 'defaultBranchRef.name',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Artifact ID',
        field: 'pom.artifactId',
        fieldType: 'string',
        sortField: 'pom.artifactId',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Version',
        field: 'pom.version',
        fieldType: 'string',
        sortField: 'pom.version',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Parent Artifact',
        field: 'pom.parent.artifactId',
        fieldType: 'string',
        sortField: 'pom.parent.artifactId',
        linkField: null,
        sortable: true,
        default: true,
      },  
      {
        name: 'Parent Version',
        field: 'pom.parent.version',
        fieldType: 'string',
        sortField: 'pom.parent.version',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Last Committer',
        field: 'lastCommitMainBranch.author.email',
        fieldType: 'longstring',
        sortField: 'lastCommitMainBranch.author.email',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Last Commit message',
        field: 'lastCommitMainBranch.messageHeadline',
        fieldType: 'longstring',
        sortField: 'lastCommitMainBranch.messageHeadline.keyword',
        linkField: null,
        sortable: true,
        default: true,
      },      
    ],
  },
};

export default config;
