// Zencrepes configuration for that entity
const entity = 'githubReleases';
const config = {
  id: entity,
  name: 'Releases',
  platform: 'github',
  active: true,
  facets: [
    {
      facetType: 'date',
      field: 'createdAt',
      name: 'Created',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'date',
      field: 'updatedAt',
      name: 'Updated',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'date',
      field: 'publishedAt',
      name: 'Published',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'boolean',
      field: 'isDraft',
      name: 'Draft',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'boolean',
      field: 'isPrerelease',
      name: 'Prerelease',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'author.login',
      name: 'Author',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'name.keyword',
      name: 'Name',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'tagName.keyword',
      name: 'Tag Name',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'repository.name.keyword',
      name: 'Repository',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'repository.owner.login',
      name: 'Organization',
      nullValue: 'EMPTY',
      default: true,
    },
  ],
  tableConfig: {
    itemsType: 'Github Releases',
    defaultSortField: 'name.keyword',
    columns: [
      {
        name: 'id',
        field: 'id',
        sortField: 'id',
        sortable: false,
        default: false,
      },
      {
        name: 'Created At',
        field: 'createdAt',
        fieldType: 'date',
        sortField: 'createdAt',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Published At',
        field: 'publishedAt',
        fieldType: 'date',
        sortField: 'publishedAt',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Repository',
        field: 'repository.name',
        sortField: 'repository.name.keyword',
        linkField: 'repository.url',
        sortable: true,
        default: true,
      },
      {
        name: 'Organization',
        field: 'repository.owner.login',
        sortField: 'repository.owner.login.keyword',
        linkField: 'repository.owner.url',
        sortable: true,
        default: true,
      },
      {
        name: 'Name',
        field: 'name',
        sortField: 'name.keyword',
        linkField: 'url',
        sortable: true,
        default: true,
      },
      {
        name: 'Tag Name',
        field: 'tagName',
        sortField: 'tagName.keyword',
        linkField: 'url',
        sortable: true,
        default: true,
      },
      {
        name: 'Draft',
        field: 'isDraft',
        fieldType: 'boolean',
        sortField: 'isDraft',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Pre-Release',
        field: 'isPrerelease',
        fieldType: 'boolean',
        sortField: 'isPrerelease',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Url',
        field: 'url',
        sortField: 'url',
        linkField: null,
        sortable: false,
        default: false,
      },
    ],
  },
};

export default config;
