// Zencrepes configuration for that entity
const entity = 'bambooRuns';
const config = {
  id: entity,
  name: 'Bamboo Runs',
  platform: 'bamboo',
  active: true,
  facets: [
    {
      facetType: 'date',
      field: 'startedAt',
      name: 'Started At',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'boolean',
      field: 'successful',
      name: 'Successful',
      nullValue: 'EMPTY',
      nullFilter: '',
      default: true,
    },  
    {
      facetType: 'term',
      field: 'plan.name.keyword',
      name: 'Plan Name',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'plan.id',
      name: 'Plan ID',
      nullValue: 'EMPTY',
      default: true,
    },    
    {
      facetType: 'term',
      field: 'plan.project.name.keyword',
      name: 'Project Name',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'plan.project.id',
      name: 'Project ID',
      nullValue: 'EMPTY',
      default: true,
    },     
  ],
  tableConfig: {
    itemsType: 'Bamboo Runs',
    defaultSortField: 'startedAt',
    columns: [
      {
        name: 'id',
        field: 'id',
        fieldType: 'string',
        sortField: 'id',
        sortable: false,
        default: false,
      },
      {
        name: 'Project ID',
        field: 'plan.project.id',
        fieldType: 'string',
        sortField: 'plan.project.id',
        linkField: 'url',
        sortable: true,
        default: true,
      },
      {
        name: 'Plan Name',
        field: 'plan.name',
        fieldType: 'string',
        sortField: 'plan.name.keyword',
        linkField: 'url',
        sortable: true,
        default: true,
      }, 
      {
        name: '#',
        field: 'number',
        fieldType: 'number',
        sortField: 'number',
        linkField: 'url',
        sortable: true,
        default: true,
      },       
      {
        name: 'Started At',
        field: 'startedAt',
        fieldType: 'datetime',
        sortField: 'startedAt',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Duration (s)',
        field: 'duration',
        fieldType: 'number',
        sortField: 'duration',
        linkField: 'url',
        sortable: true,
        default: true,
      },      
      {
        name: 'Successful',
        field: 'successful',
        fieldType: 'boolean',
        sortField: 'successful',
        sortable: true,
        default: true,
      },
      {
        name: 'Total',
        field: 'runTotal',
        fieldType: 'string',
        sortField: 'runTotal',
        sortable: true,
        default: true,
      },   
      {
        name: 'Run Success',
        field: 'runSuccess',
        fieldType: 'string',
        sortField: 'runSuccess',
        sortable: true,
        default: true,
      },   
      {
        name: 'Run Failure',
        field: 'runFailure',
        fieldType: 'string',
        sortField: 'runFailure',
        sortable: true,
        default: true,
      },
      {
        name: 'Run Skipped',
        field: 'runSkipped',
        fieldType: 'string',
        sortField: 'runSkipped',
        sortable: true,
        default: true,
      },
    ],
  },
};

export default config;
