const aggsState = [
  // Keep
  { field: 'state', active: true, show: true },
  { field: 'assignees__edges__node__login', active: true, show: true },
  { field: 'author__login', active: true, show: true },
  { field: 'updatedAt', active: true, show: true },
  { field: 'closedAt', active: true, show: true },
  { field: 'createdAt', active: true, show: true },
  // { field: 'labels__edges__node__name', active: true, show: true },
  // { field: 'repository__name', active: true, show: true },
  // { field: 'milestone__state', active: true, show: true },
  // { field: 'milestone__title', active: true, show: true },
  // {
  //   field: 'projectCards__edges__node__project__name',
  //   active: true,
  //   show: true,
  // },
  // { field: 'repository__owner__login', active: true, show: true },
  { field: 'comments__totalCount', active: true, show: true },
  { field: 'participants__totalCount', active: true, show: true },
  { field: 'projectCards__totalCount', active: true, show: true },
];

const columnsState = {
  type: 'githubIssues',
  keyField: 'id',
  defaultSorted: [{ id: 'createdAt', desc: false }],
  columns: [
    {
      show: true,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'assignees.edges.node.login',
      accessor: 'assignees.edges.node.login',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'assignees.edges.node.name',
      accessor: 'assignees.edges.node.name',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'assignees.edges.node.url',
      accessor: 'assignees.edges.node.url',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'assignees.totalCount',
      accessor: 'assignees.totalCount',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'author.avatarUrl',
      accessor: 'author.avatarUrl',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'author.login',
      accessor: 'author.login',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'author.url',
      accessor: 'author.url',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'body',
      accessor: 'body',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'closedAt',
      accessor: 'closedAt',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'comments.totalCount',
      accessor: 'comments.totalCount',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'createdAt',
      accessor: 'createdAt',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'databaseId',
      accessor: 'databaseId',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'labels.edges.node.color',
      accessor: 'labels.edges.node.color',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'labels.edges.node.description',
      accessor: 'labels.edges.node.description',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'labels.edges.node.id',
      accessor: 'labels.edges.node.id',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'labels.edges.node.name',
      accessor: 'labels.edges.node.name',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'labels.totalCount',
      accessor: 'labels.totalCount',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.closedAt',
      accessor: 'milestone.closedAt',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.createdAt',
      accessor: 'milestone.createdAt',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.description',
      accessor: 'milestone.description',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.dueOn',
      accessor: 'milestone.dueOn',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.id',
      accessor: 'milestone.id',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.issues.totalCount',
      accessor: 'milestone.issues.totalCount',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.number',
      accessor: 'milestone.number',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.state',
      accessor: 'milestone.state',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.title',
      accessor: 'milestone.title',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.updatedAt',
      accessor: 'milestone.updatedAt',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'milestone.url',
      accessor: 'milestone.url',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'nodeId',
      accessor: 'nodeId',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'number',
      accessor: 'number',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'participants.totalCount',
      accessor: 'participants.totalCount',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'projectCards.edges.node.id',
      accessor: 'projectCards.edges.node.id',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'projectCards.edges.node.project.id',
      accessor: 'projectCards.edges.node.project.id',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'projectCards.edges.node.project.name',
      accessor: 'projectCards.edges.node.project.name',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'projectCards.totalCount',
      accessor: 'projectCards.totalCount',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'repository.databaseId',
      accessor: 'repository.databaseId',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'repository.id',
      accessor: 'repository.id',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'repository.name',
      accessor: 'repository.name',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'repository.owner.id',
      accessor: 'repository.owner.id',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'repository.owner.login',
      accessor: 'repository.owner.login',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'repository.owner.url',
      accessor: 'repository.owner.url',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'repository.url',
      accessor: 'repository.url',
    },
    {
      show: true,
      type: 'string',
      sortable: true,
      canChangeShow: true,
      query: null,
      jsonPath: null,
      id: null,
      field: 'state',
      accessor: 'state',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.createdAt',
      accessor: 'timelineItems.edges.node.createdAt',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.id',
      accessor: 'timelineItems.edges.node.id',
    },
    {
      show: false,
      type: 'boolean',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.isCrossRepository',
      accessor: 'timelineItems.edges.node.isCrossRepository',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.referencedAt',
      accessor: 'timelineItems.edges.node.referencedAt',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.resourcePath',
      accessor: 'timelineItems.edges.node.resourcePath',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.source.id',
      accessor: 'timelineItems.edges.node.source.id',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.source.number',
      accessor: 'timelineItems.edges.node.source.number',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.source.state',
      accessor: 'timelineItems.edges.node.source.state',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.source.title',
      accessor: 'timelineItems.edges.node.source.title',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.source.typename',
      accessor: 'timelineItems.edges.node.source.typename',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.source.url',
      accessor: 'timelineItems.edges.node.source.url',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.target.id',
      accessor: 'timelineItems.edges.node.target.id',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.target.number',
      accessor: 'timelineItems.edges.node.target.number',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.target.state',
      accessor: 'timelineItems.edges.node.target.state',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.target.title',
      accessor: 'timelineItems.edges.node.target.title',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.target.typename',
      accessor: 'timelineItems.edges.node.target.typename',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.target.url',
      accessor: 'timelineItems.edges.node.target.url',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.url',
      accessor: 'timelineItems.edges.node.url',
    },
    {
      show: false,
      type: 'boolean',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.edges.node.willCloseTarget',
      accessor: 'timelineItems.edges.node.willCloseTarget',
    },
    {
      show: false,
      type: 'number',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'timelineItems.totalCount',
      accessor: 'timelineItems.totalCount',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: true,
      query: null,
      jsonPath: null,
      id: null,
      field: 'title',
      accessor: 'title',
    },
    {
      show: false,
      type: 'date',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'updatedAt',
      accessor: 'updatedAt',
    },
    {
      show: false,
      type: 'string',
      sortable: true,
      canChangeShow: false,
      query: null,
      jsonPath: null,
      id: null,
      field: 'url',
      accessor: 'url',
    },
  ],
};

const matchBoxState = [
  {
    displayName: 'githubIssues',
    field: '',
    isActive: true,
    keyField: 'nodeId',
    searchFields: ['state', 'title'],
  },
];

const extendedMapping = [
  {
    field: 'assignees',
    type: 'object',
    displayName: 'Assignees',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.edges',
    type: 'object',
    displayName: 'Assignees Edges',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.edges.node',
    type: 'object',
    displayName: 'Assignees Edges Node',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.edges.node.avatarUrl',
    type: 'keyword',
    displayName: 'Assignees Edges Node Avatar Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.edges.node.id',
    type: 'id',
    displayName: 'Assignees Edges Node Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.edges.node.login',
    type: 'keyword',
    displayName: 'Assignees',
    active: true,
    isArray: true,
    primaryKey: false,
    quickSearchEnabled: true,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.edges.node.name',
    type: 'text',
    displayName: 'Assignees Edges Node Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.edges.node.url',
    type: 'keyword',
    displayName: 'Assignees Edges Node Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'assignees.totalCount',
    type: 'long',
    displayName: 'Assignees Total Count',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'author',
    type: 'object',
    displayName: 'Author',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'author.avatarUrl',
    type: 'keyword',
    displayName: 'Author Avatar Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'author.login',
    type: 'keyword',
    displayName: 'Author Login',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'author.url',
    type: 'keyword',
    displayName: 'Author Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'body',
    type: 'keyword',
    displayName: 'Body',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'closedAt',
    type: 'date',
    displayName: 'Closed At',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'comments',
    type: 'object',
    displayName: 'Comments',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'comments.totalCount',
    type: 'long',
    displayName: 'Comments Total Count',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'createdAt',
    type: 'date',
    displayName: 'Created At',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'databaseId',
    type: 'long',
    displayName: 'Database Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels',
    type: 'object',
    displayName: 'Labels',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels.edges',
    type: 'object',
    displayName: 'Labels Edges',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels.edges.node',
    type: 'object',
    displayName: 'Labels Edges Node',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels.edges.node.color',
    type: 'keyword',
    displayName: 'Labels Edges Node Color',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels.edges.node.description',
    type: 'text',
    displayName: 'Labels Edges Node Description',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels.edges.node.id',
    type: 'id',
    displayName: 'Labels Edges Node Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels.edges.node.name',
    type: 'text',
    displayName: 'Labels Edges Node Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'labels.totalCount',
    type: 'long',
    displayName: 'Labels Total Count',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone',
    type: 'object',
    displayName: 'Milestone',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.closedAt',
    type: 'date',
    displayName: 'Milestone Closed At',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.createdAt',
    type: 'date',
    displayName: 'Milestone Created At',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.description',
    type: 'text',
    displayName: 'Milestone Description',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.dueOn',
    type: 'date',
    displayName: 'Milestone Due On',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.id',
    type: 'id',
    displayName: 'Milestone Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.issues',
    type: 'object',
    displayName: 'Milestone Issues',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.issues.totalCount',
    type: 'long',
    displayName: 'Milestone Issues Total Count',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.number',
    type: 'long',
    displayName: 'Milestone Number',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.state',
    type: 'keyword',
    displayName: 'Milestone State',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.title',
    type: 'text',
    displayName: 'Milestone Title',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.updatedAt',
    type: 'date',
    displayName: 'Milestone Updated At',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'milestone.url',
    type: 'keyword',
    displayName: 'Milestone Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'nodeId',
    type: 'keyword',
    displayName: 'Node Id',
    active: true,
    isArray: false,
    primaryKey: true,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'number',
    type: 'long',
    displayName: 'Number',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'participants',
    type: 'object',
    displayName: 'Participants',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'participants.totalCount',
    type: 'long',
    displayName: 'Participants Total Count',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards',
    type: 'object',
    displayName: 'Project Cards',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards.edges',
    type: 'object',
    displayName: 'Project Cards Edges',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards.edges.node',
    type: 'object',
    displayName: 'Project Cards Edges Node',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards.edges.node.id',
    type: 'id',
    displayName: 'Project Cards Edges Node Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards.edges.node.project',
    type: 'object',
    displayName: 'Project Cards Edges Node Project',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards.edges.node.project.id',
    type: 'id',
    displayName: 'Project Cards Edges Node Project Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards.edges.node.project.name',
    type: 'text',
    displayName: 'Project Cards Edges Node Project Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'projectCards.totalCount',
    type: 'long',
    displayName: 'Project Cards Total Count',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository',
    type: 'object',
    displayName: 'Repository',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.databaseId',
    type: 'long',
    displayName: 'Repository Database Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.id',
    type: 'id',
    displayName: 'Repository Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.name',
    type: 'text',
    displayName: 'Repository Name',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.owner',
    type: 'object',
    displayName: 'Repository Owner',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.owner.id',
    type: 'id',
    displayName: 'Repository Owner Id',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.owner.login',
    type: 'keyword',
    displayName: 'Repository Owner Login',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.owner.url',
    type: 'keyword',
    displayName: 'Repository Owner Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'repository.url',
    type: 'keyword',
    displayName: 'Repository Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'state',
    type: 'keyword',
    displayName: 'State',
    active: true,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: true,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'title',
    type: 'text',
    displayName: 'Title',
    active: true,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: true,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'updatedAt',
    type: 'date',
    displayName: 'Updated At',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
  {
    field: 'url',
    type: 'keyword',
    displayName: 'Url',
    active: false,
    isArray: false,
    primaryKey: false,
    quickSearchEnabled: false,
    unit: null,
    displayValues: {},
    rangeStep: 1,
  },
];
