// Zencrepes configuration for that entity
const entity = 'circleciInsights';
const config = {
  id: entity,
  name: 'Circleci Insights',
  platform: 'circleci',
  active: true,
  facets: [
    {
      facetType: 'date',
      field: 'started_at',
      name: 'Started At',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'job.name.keyword',
      name: 'Job Name',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'status',
      name: 'Job Status',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'job.workflow.name.keyword',
      name: 'Workflow Name',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'job.workflow.source.repository.name.keyword',
      name: 'Repository',
      nullValue: 'EMPTY',
      default: true,
    },
    {
      facetType: 'term',
      field: 'job.workflow.source.repository.owner.login',
      name: 'Organization',
      nullValue: 'EMPTY',
      default: true,
    },
  ],
  tableConfig: {
    itemsType: 'Circleci Insights',
    defaultSortField: 'started_at',
    columns: [
      {
        name: 'id',
        field: 'id',
        sortField: 'id',
        sortable: false,
        default: false,
      },
      {
        name: 'Job Name',
        field: 'job.name',
        sortField: 'job.name.keyword',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Workflow Name',
        field: 'job.workflow.name',
        sortField: 'job.workflow.name.keyword',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Started At',
        field: 'started_at',
        sortField: 'started_at',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Duration',
        field: 'duration',
        sortField: 'duration',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Credits Used',
        field: 'credits_used',
        sortField: 'credits_used',
        linkField: null,
        sortable: true,
        default: true,
      },
      {
        name: 'Repository',
        field: 'job.workflow.source.repository.name',
        sortField: 'job.workflow.source.repository.name.keyword',
        linkField: 'job.workflow.source.repository.url',
        sortable: true,
        default: true,
      },
      {
        name: 'Organization',
        field: 'job.workflow.source.repository.owner.login',
        sortField: 'job.workflow.source.repository.owner.login.keyword',
        linkField: 'job.workflow.source.repository.owner.url',
        sortable: true,
        default: true,
      },
      {
        name: 'Repo URL',
        field: 'job.workflow.source.repository.url',
        sortField: null,
        linkField: null,
        sortable: false,
        default: false,
      },
    ],
  },
};

export default config;
