name: Publish Release to Registry
on:
  release:
    types: [published]

jobs:
  npm_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: yarn
      - run: npm -g install typescript@4.2.3
      - run: npm -g install @oclif/dev-cli @oclif/help
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}
      - run: tsc -b
      - run: oclif-dev manifest
      - run: ls -lah ./
      - run: npm publish --access public

  npm_test:
    needs: [npm_publish]

    runs-on: ubuntu-latest

    container:
      image: node:20-alpine

    steps:
      - run: npm -g install zindexer@${{ github.event.release.tag_name }}
      - run: zindexer --help
      - run: zindexer startup

  docker:
    needs: [npm_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: zencrepes/zindexer
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: 'latest,${{ env.RELEASE_VERSION }}'
